## Deliverable 2. Create a Customer Travel Destinations Map.

In [8]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [9]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
city_data_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Itupiranga,BR,-5.1347,-49.3267,78.80,89,75,5.75,broken clouds
1,1,Jamestown,US,42.0970,-79.2353,62.60,14,1,8.52,clear sky
2,2,Kharp,RU,66.8014,65.8081,-0.31,98,100,3.87,overcast clouds
3,3,Sun Prairie,US,43.1836,-89.2137,59.00,41,90,9.22,overcast clouds
4,4,Dingle,PH,10.9995,122.6711,76.46,87,100,8.84,overcast clouds
...,...,...,...,...,...,...,...,...,...,...
711,711,Santos Dumont,BR,-21.4567,-43.5525,78.80,57,40,4.61,scattered clouds
712,712,Birao,CF,10.2849,22.7882,88.68,30,99,5.75,overcast clouds
713,713,Djibo,BF,14.1022,-1.6306,91.29,14,100,9.75,overcast clouds
714,714,Harrisonburg,US,38.4496,-78.8689,64.99,29,0,2.86,clear sky
715,715,Lima,PE,-12.0432,-77.0282,78.01,64,0,10.36,clear sky

In [10]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
print("What is the minimum temperature?")
min_temp = float(input("min_temp: "))
print("What is the maximum temperature?")
max_temp = float(input("max_temp: "))

What is the minimum temperature?
min_temp: 75
What is the maximum temperature?
max_temp: 90

In [11]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] >= min_temp) &
                                       (city_data_df["Max Temp"] <= max_temp)]
preferred_cities_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Itupiranga,BR,-5.1347,-49.3267,78.80,89,75,5.75,broken clouds
4,4,Dingle,PH,10.9995,122.6711,76.46,87,100,8.84,overcast clouds
10,10,Rio Grande,BR,-32.0350,-52.0986,75.20,69,75,11.50,broken clouds
16,16,Valparaiso,CL,-33.0393,-71.6273,80.60,38,0,12.66,clear sky
17,17,Axim,GH,4.8699,-2.2405,79.90,82,100,11.41,overcast clouds
...,...,...,...,...,...,...,...,...,...,...
702,702,Nova Vicosa,BR,-17.8919,-39.3719,80.60,72,18,6.98,few clouds
703,703,Cassilandia,BR,-19.1133,-51.7342,87.82,41,18,7.96,few clouds
711,711,Santos Dumont,BR,-21.4567,-43.5525,78.80,57,40,4.61,scattered clouds
712,712,Birao,CF,10.2849,22.7882,88.68,30,99,5.75,overcast clouds
715,715,Lima,PE,-12.0432,-77.0282,78.01,64,0,10.36,clear sky

In [12]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.isnull().sum()

City_ID                0
City                   0
Country                2
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
dtype: int64

In [13]:
# 4b. Drop any empty rows and create a new DataFrame that doesnâ€™t have empty rows.
clean_cities_df = preferred_cities_df.dropna()
clean_cities_df

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Itupiranga,BR,-5.1347,-49.3267,78.80,89,75,5.75,broken clouds
4,4,Dingle,PH,10.9995,122.6711,76.46,87,100,8.84,overcast clouds
10,10,Rio Grande,BR,-32.0350,-52.0986,75.20,69,75,11.50,broken clouds
16,16,Valparaiso,CL,-33.0393,-71.6273,80.60,38,0,12.66,clear sky
17,17,Axim,GH,4.8699,-2.2405,79.90,82,100,11.41,overcast clouds
...,...,...,...,...,...,...,...,...,...,...
702,702,Nova Vicosa,BR,-17.8919,-39.3719,80.60,72,18,6.98,few clouds
703,703,Cassilandia,BR,-19.1133,-51.7342,87.82,41,18,7.96,few clouds
711,711,Santos Dumont,BR,-21.4567,-43.5525,78.80,57,40,4.61,scattered clouds
712,712,Birao,CF,10.2849,22.7882,88.68,30,99,5.75,overcast clouds
715,715,Lima,PE,-12.0432,-77.0282,78.01,64,0,10.36,clear sky

In [14]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Itupiranga,BR,78.80,broken clouds,-5.1347,-49.3267,
4,Dingle,PH,76.46,overcast clouds,10.9995,122.6711,
10,Rio Grande,BR,75.20,broken clouds,-32.0350,-52.0986,
16,Valparaiso,CL,80.60,clear sky,-33.0393,-71.6273,
17,Axim,GH,79.90,overcast clouds,4.8699,-2.2405,
18,Mahebourg,MU,78.80,scattered clouds,-20.4081,57.7000,
22,Atar,MR,79.99,clear sky,20.5169,-13.0499,
23,Sao Sebastiao,BR,81.82,broken clouds,-23.7600,-45.4097,
26,Naranjal,EC,89.60,moderate rain,-2.6667,-79.6167,
30,Grand Gaube,MU,79.00,few clouds,-20.0064,57.6608,

In [15]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    
    # 6c. Get latitude and longitude from DataFrame

    lat = row["Lat"]
    lng = row["Lng"]
    params["location"]= f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index,"Hotel Name"] = hotels["results"][0]["name"]
        
    except(IndexError):
        print("Hotel not found....skipping.")

Hotel not found....skipping.
Hotel not found....skipping.
Hotel not found....skipping.
Hotel not found....skipping.
Hotel not found....skipping.
Hotel not found....skipping.
Hotel not found....skipping.
Hotel not found....skipping.
Hotel not found....skipping.
Hotel not found....skipping.
Hotel not found....skipping.
Hotel not found....skipping.
Hotel not found....skipping.
Hotel not found....skipping.
Hotel not found....skipping.
Hotel not found....skipping.
Hotel not found....skipping.
Hotel not found....skipping.
Hotel not found....skipping.
Hotel not found....skipping.

In [16]:
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Itupiranga,BR,78.80,broken clouds,-5.1347,-49.3267,Hotel Panorama
4,Dingle,PH,76.46,overcast clouds,10.9995,122.6711,SEGAYA PROPERTY
10,Rio Grande,BR,75.20,broken clouds,-32.0350,-52.0986,Hotel AtlÃ¢ntico Rio Grande
16,Valparaiso,CL,80.60,clear sky,-33.0393,-71.6273,Hotel Ultramar
17,Axim,GH,79.90,overcast clouds,4.8699,-2.2405,AXIM BEACH RESORT AND SPA
18,Mahebourg,MU,78.80,scattered clouds,-20.4081,57.7000,Shandrani Beachcomber Resort & Spa
22,Atar,MR,79.99,clear sky,20.5169,-13.0499,Oumou Elghoura
23,Sao Sebastiao,BR,81.82,broken clouds,-23.7600,-45.4097,Hotel Recanto dos PÃ¡ssaros
26,Naranjal,EC,89.60,moderate rain,-2.6667,-79.6167,Media Naranja
30,Grand Gaube,MU,79.00,few clouds,-20.0064,57.6608,Veranda Paul et Virginie Hotel & Spa

In [17]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotels_names = hotel_df.replace(r'^\s*$', np.nan, regex=True)
clean_hotel_df = clean_hotels_names.dropna()
clean_hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Itupiranga,BR,78.80,broken clouds,-5.1347,-49.3267,Hotel Panorama
4,Dingle,PH,76.46,overcast clouds,10.9995,122.6711,SEGAYA PROPERTY
10,Rio Grande,BR,75.20,broken clouds,-32.0350,-52.0986,Hotel AtlÃ¢ntico Rio Grande
16,Valparaiso,CL,80.60,clear sky,-33.0393,-71.6273,Hotel Ultramar
17,Axim,GH,79.90,overcast clouds,4.8699,-2.2405,AXIM BEACH RESORT AND SPA
...,...,...,...,...,...,...,...
696,Sindgi,IN,86.27,broken clouds,16.9167,76.2333,Kadamba Residency
702,Nova Vicosa,BR,80.60,few clouds,-17.8919,-39.3719,Pousada Porto do Sol
703,Cassilandia,BR,87.82,few clouds,-19.1133,-51.7342,Delirius Motel
711,Santos Dumont,BR,78.80,scattered clouds,-21.4567,-43.5525,Hotel - Leiteria SÃ£o Luiz
715,Lima,PE,78.01,clear sky,-12.0432,-77.0282,Gran Hotel Bolivar Lima

In [18]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [19]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} Â°F</dd>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [20]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))